services:
  # ===================== PostgreSQL =====================

  auth-postgres-db:
    image: postgres:17
    container_name: auth-postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d auth"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data

  profile-postgres-db:
    image: postgres:17
    container_name: profile-postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: profile
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d profile"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - profile_postgres_data:/var/lib/postgresql/data

  post-postgres-db:
    image: postgres:17
    container_name: post-postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: post_outbox
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d post_outbox"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - post_postgres_data:/var/lib/postgresql/data


  # ======================== Redis ========================

  profile-redis-db:
    image: redis:7
    container_name: profile-redis
    restart: on-failure
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - profile_redis_data:/data

  post-redis-db:
    image: redis:7
    container_name: post-redis
    restart: on-failure
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - post_redis_data:/data


  # ======================== Scylla ========================

  post-scylla-db:
    image: scylladb/scylla:latest
    container_name: post-scylla
    restart: unless-stopped
    command: --smp 2 --memory 2G
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'SELECT now() FROM system.local' || exit 1"]
      interval: 10s
      timeout: 10s
      start_period: 60s
      retries: 15
    volumes:
      - post_scylla_data:/var/lib/scylla

  post-scylla-init:
    image: scylladb/scylla:latest
    container_name: post-scylla-init
    restart: on-failure
    depends_on:
      post-scylla-db:
        condition: service_healthy
    volumes:
      - ../Services/Posts/Scripts/init.cql:/init.cql
    entrypoint: ["cqlsh", "post-scylla-db", "-f", "/init.cql"]

  # interaction-scylla-db:
  #   image: scylladb/scylla:6.2
  #   container_name: interaction-scylla
  #   restart: unless-stopped
  #   command: --smp 2 --memory 2G
  #   healthcheck:
  #     test: ["CMD-SHELL", "cqlsh -e 'SELECT now() FROM system.local' || exit 1"]
  #     interval: 10s
  #     timeout: 10s
  #     start_period: 60s
  #     retries: 15
  #   volumes:
  #     - interaction_scylla_data:/var/lib/scylla


  # ======================= RabbitMQ =======================

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: on-failure
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 10s
      retries: 5
    ports:
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

# ========================= Services ========================

  gateway-yarp:
    build:
      context: ..
      dockerfile: Services/Gateway/Gateway.YARP/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    env_file:
      - Gateway/Gateway.YARP/.env
    depends_on:
      auth-api:
        condition: service_healthy
      profiles-api:
        condition: service_healthy
      posts-api:
        condition: service_healthy
      # interaction-api:
      #   condition: service_healthy

  auth-api:
    build:
      context: ..
      dockerfile: Services/Auth/Auth.API/Dockerfile
    restart: on-failure
    env_file:
      - Auth/Auth.API/.env
    healthcheck:
      test: ["CMD", "bash", "-c", "cat < /dev/tcp/localhost/8080"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      auth-postgres-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  profiles-api:
    build:
      context: ..
      dockerfile: Services/Profiles/Profiles.API/Dockerfile
    restart: on-failure
    env_file:
      - Profiles/Profiles.API/.env
    healthcheck:
      test: ["CMD", "bash", "-c", "cat < /dev/tcp/localhost/8080"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      profile-postgres-db:
        condition: service_healthy
      profile-redis-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  posts-api:
    build:
      context: ..
      dockerfile: Services/Posts/Posts.API/Dockerfile
    restart: on-failure
    env_file:
      - Posts/Posts.API/.env
    healthcheck:
      test: ["CMD", "bash", "-c", "cat < /dev/tcp/localhost/8080"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      post-postgres-db:
        condition: service_healthy
      post-scylla-init:
        condition: service_completed_successfully
      post-redis-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  # interaction-api:
  #   build:
  #     context: ..
  #     dockerfile: Services/Interaction/Interaction.API/Dockerfile
  #   restart: on-failure
  #   env_file:
  #     - Interaction/Interaction.API/.env
  #   healthcheck:
  #     test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #     interaction-scylla-db:
  #       condition: service_healthy

# ========================= VOLUMES =========================

volumes:
  auth_postgres_data:
  profile_postgres_data:
  post_postgres_data:

  profile_redis_data:
  post_redis_data:

  post_scylla_data:
  # interaction_scylla_data:

  rabbitmq_data:
