services:
  # ===================== PostgreSQL =====================

  auth-postgres-db:
    image: postgres:17
    container_name: auth-postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth
    ports:
      - "5433:5432"
    networks:
      - appnet
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data

  profile-postgres-db:
    image: postgres:17
    container_name: profile-postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: profile
    ports:
      - "5434:5432"
    networks:
      - appnet
    volumes:
      - profile_postgres_data:/var/lib/postgresql/data

  post-postgres-db:
    image: postgres:17
    container_name: post-postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: post_outbox
    ports:
      - "5435:5432"
    networks:
      - appnet
    volumes:
      - post_postgres_data:/var/lib/postgresql/data


  # ======================== Redis ========================

  profile-redis-db:
    image: redis:latest
    container_name: profile-redis
    restart: on-failure
    ports:
      - "6380:6379"
    networks:
      - appnet
    volumes:
      - profile_redis_data:/data

  post-redis-db:
    image: redis:latest
    container_name: post-redis
    restart: on-failure
    ports:
      - "6381:6379"
    networks:
      - appnet
    volumes:
      - post_redis_data:/data


  # ======================== Scylla ========================

  post-scylla-db:
    image: scylladb/scylla:latest
    container_name: post-scylla
    restart: unless-stopped
    ports:
      - "9043:9042"
    command: --smp 2 --memory 2G
    networks:
      - appnet
    volumes:
      - post_scylla_data:/var/lib/scylla

  interaction-scylla-db:
    image: scylladb/scylla:latest
    container_name: interaction-scylla
    restart: unless-stopped
    ports:
      - "9044:9042"
    command: --smp 2 --memory 2G
    networks:
      - appnet
    volumes:
      - interaction_scylla_data:/var/lib/scylla


  # ======================= RabbitMQ =======================

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: on-failure
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - appnet
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
        
# ========================= Services ========================

  gateway-yarp:
    build:
      context: ..
      dockerfile: Services/Gateway/Gateway.YARP/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    env_file:
      - Gateway/Gateway.YARP/.env
    depends_on:
      - auth-api
      - profiles-api
      - posts-api
      - interaction-api
    networks:
      - appnet

  auth-api:
    build:
      context: ..
      dockerfile: Services/Auth/Auth.API/Dockerfile
    restart: on-failure
    env_file:
      - Auth/Auth.API/.env
    depends_on:
      - auth-postgres-db
      - rabbitmq
    networks:
      - appnet

  profiles-api:
    build:
      context: ..
      dockerfile: Services/Profiles/Profiles.API/Dockerfile
    restart: on-failure
    env_file:
      - Profiles/Profiles.API/.env
    depends_on:
      - profile-postgres-db
      - profile-redis-db
      - rabbitmq
    networks:
      - appnet

  posts-api:
    build:
      context: ..
      dockerfile: Services/Posts/Posts.API/Dockerfile
    restart: on-failure
    env_file:
      - Posts/Posts.API/.env
    depends_on:
      - post-postgres-db
      - post-scylla-db
      - post-redis-db
      - rabbitmq
    networks:
      - appnet

  interaction-api:
    build:
      context: ..
      dockerfile: Services/Interaction/Interaction.API/Dockerfile
    restart: on-failure
    env_file:
      - Interaction/Interaction.API/.env
    depends_on:
      - rabbitmq
      - interaction-scylla-db
    networks:
      - appnet

# ========================= VOLUMES =========================

volumes:
  auth_postgres_data:
  profile_postgres_data:
  post_postgres_data:

  profile_redis_data:
  post_redis_data:

  post_scylla_data:
  interaction_scylla_data:

  rabbitmq_data:
  
# ========================= NETWORKS =========================

networks:
  appnet:
    driver: bridge
